dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

language: node_js
node_js:
  - "8"
  - stable
cache: yarn
script:
  - yarn run test
  - yarn run test:e2e
jobs:
  include:
    - stage: Produce Coverage
      node_js: stable
      script: jest --collectCoverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage