Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder '..', '/home/vagrant/workspace', disabled: false
  config.vm.network :forwarded_port, guest:1337, host:1337
end

